---
- name: Create alloy configuration file, positions file, and Docker script
  hosts: all
  become: true
  vars:
    loki_endpoint: "{{ lookup('env', 'LOKI_ENDPOINT') }}"

  tasks:
    - name: Ensure the directory exists
      file:
        path: /home/ubuntu/mount/alloy
        state: directory
        mode: '0755'

    - name: Create the alloy config file
      copy:
        dest: /home/ubuntu/mount/alloy/config.alloy
        content: |
          discovery.docker "logs_integrations_docker" {
              host             = "unix:///var/run/docker.sock"
              refresh_interval = "5s"
          }

          discovery.relabel "logs_integrations_docker" {
              targets = []

              rule {
                  target_label = "app"
              }

              rule {
                  target_label = "instance"
                  replacement  = constants.hostname
              }

              rule {
                  source_labels = ["__meta_docker_container_name"]
                  regex         = "/(.*)"
                  target_label  = "app"
              }

              rule {
                  source_labels = ["__meta_docker_container_log_stream"]
                  target_label  = "stream"
              }
          }

          loki.source.docker "logs_integrations_docker" {
              host             = "unix:///var/run/docker.sock"
              targets          = discovery.docker.logs_integrations_docker.targets
              forward_to       = [loki.write.grafana_loki.receiver]
              relabel_rules    = discovery.relabel.logs_integrations_docker.rules
              refresh_interval = "5s"
          }

          loki.write "grafana_loki" {
              endpoint {
                  url = "{{ loki_endpoint }}"
              }
          }
        mode: '0644'

    - name: Ensure positions.yml file exists
      copy:
        dest: /home/ubuntu/mount/alloy/positions.yml
        content: ""
        mode: '0664'
        owner: "1000"
        group: "1000"
        force: no  # Prevents overwriting existing positions.yml

    - name: Copy docker-alloy-ap-south-1.sh script
      copy:
        src: docker-alloy-ap-south-1.sh
        dest: /home/ubuntu/mount/alloy/docker-alloy-ap-south-1.sh
        mode: '0755'  # Ensure it's executable%
